name: Multistage Environment

on:
  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '17'
          distribution: 'microsoft'
      - name: Build and Deploy to Dev
        run: |
          echo "Deploying to development environment..."
          echo "Using DEV_URL variable: ${{ vars.VARIABLE }}"
          echo "Using DEV_API_KEY secret: ${{ secrets.DEV_SECRET }}"
        working-directory: ./Spring-boot-E-Commerce-Project/
  
  test:
    runs-on: ubuntu-latest
    needs: [dev]
    environment:
      name: test
    steps:
      - name: Deploy to Test
        run: |
          echo "Deploying to test environment..."
          echo "Using TEST_DB_URL variable: ${{ vars.TEST_VARIABLE }}"
          echo "Using TEST_SECRET secret: ${{ secrets.TEST_SECRET }}"

  staging:
    runs-on: ubuntu-latest
    needs: [test]
    environment:
      name: staging
    steps:
      - name: Deploy to Staging
        run: |
          echo "Deploying to staging environment..."
          echo "Using STAGING_URL variable: ${{ vars.STAGING_VARIABLE }}"
          echo "Using STAGING_SECRET secret: ${{ secrets.STAGING_SECRET }}"
          
  prod:
    runs-on: ubuntu-latest
    needs: [staging]
    environment:
      name: prod
    steps:
      - name: Deploy to Production
        run: |
          echo "Deploying to production environment..."
          echo "Using PROD_URL variable: ${{ vars.PROD_VARIABLE }}"
          echo "Using PROD_SECRET secret: ${{ secrets.PROD_SECRET }}"
